services:
  ss-zapret:
    image: vernette/ss-zapret:v70.5
    container_name: zapret-proxy
    cap_add:
      - NET_ADMIN
    ports:
      - "${SS_PORT}:${SS_PORT}"
    volumes:
      - ./config:/opt/zapret/config
    environment:
      - SS_PORT=${SS_PORT}
      - SS_PASSWORD=${SS_PASSWORD}
      - SS_ENCRYPT_METHOD=${SS_ENCRYPT_METHOD}
      - SS_TIMEOUT=${SS_TIMEOUT}
    restart: unless-stopped
