services:
  socks-zapret:
    build:
      context: .
      args:
        ZAPRET_TAG: "v70.5"  # https://github.com/bol-van/zapret/releases
    container_name: zapret-proxy
    cap_add:
      - NET_ADMIN
    ports:
      - "127.0.0.1:${SS_PORT}:${SS_PORT}"
    volumes:
      - ./config:/opt/zapret/config
    environment:
      - SS_PORT=${SS_PORT}
      - SS_PASSWORD=${SS_PASSWORD}
      - SS_ENCRYPT_METHOD=${SS_ENCRYPT_METHOD}
      - SS_TIMEOUT=${SS_TIMEOUT}
    restart: unless-stopped
