services:
  ss-zapret:
    image: vernette/ss-zapret:latest
    container_name: zapret-proxy
    cap_add:
      - NET_ADMIN
    ports:
      - "${SS_PORT}:${SS_PORT}"
    volumes:
      - ./config:/opt/zapret/config
    environment:
      - SS_PORT=${SS_PORT}
      - SS_PASSWORD=${SS_PASSWORD}
      - SS_ENCRYPT_METHOD=${SS_ENCRYPT_METHOD}
      - SS_TIMEOUT=${SS_TIMEOUT}
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "${SS_PORT}"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
