services:
  ss-zapret:
    image: vernette/ss-zapret:latest
    container_name: zapret-proxy
    restart: unless-stopped
    environment:
      - SS_PORT=${SS_PORT}
      - SS_PASSWORD=${SS_PASSWORD}
      - SS_ENCRYPT_METHOD=${SS_ENCRYPT_METHOD}
      - SS_TIMEOUT=${SS_TIMEOUT}
      - SOCKS_PORT=${SOCKS_PORT}
      - SS_VERBOSE=1
    ports:
      - "127.0.0.1:${SS_PORT}:${SS_PORT}"
      - "127.0.0.1:${SOCKS_PORT}:${SOCKS_PORT}"
    volumes:
      - ./config:/opt/zapret/config
    healthcheck:
      test: [
        "CMD-SHELL",
        "nc -z localhost ${SS_PORT} && nc -z localhost ${SOCKS_PORT} || exit 1"
      ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 3s
    cap_add:
      - NET_ADMIN
